name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build the app
        run: ./scripts/buildprod.sh

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      # Build and push Docker image to Google Artifact Registry
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag asia-southeast1-docker.pkg.dev/notely-439703/notely-ar-repo/notely:latest .

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image asia-southeast1-docker.pkg.dev/notely-439703/notely-ar-repo/notely:latest \
            --region asia-southeast1 \
            --allow-unauthenticated \
            --project notely-439703 \
            --max-instances=4
